export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>MiAppAngular</title>
  <base href="/icc-ppw-u2-01Fundamentos/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles-5INURTSO.css"><style ng-app-id="ng">nav[_ngcontent-ng-c584486]{background-color:#159;padding:1rem;overflow:hidden}a[_ngcontent-ng-c584486]{color:#fff;text-decoration:none;margin-right:1rem;font-weight:700}a.active[_ngcontent-ng-c584486]{color:#ff0;text-decoration:underline}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click","submit","input","compositionstart","compositionend"],["blur"]);</script>
  <app-root ng-version="20.3.9" ngh="2" ng-server-context="ssg"><app-nav-bar _nghost-ng-c584486 ngh="0"><nav _ngcontent-ng-c584486><a _ngcontent-ng-c584486 routerlink routerlinkactive="active" href="/icc-ppw-u2-01Fundamentos/" class jsaction="click:;">Home</a><a _ngcontent-ng-c584486 routerlink="/perfil" routerlinkactive="active" href="/icc-ppw-u2-01Fundamentos/perfil" class jsaction="click:;">Perfil</a><a _ngcontent-ng-c584486 routerlink="/proyectos" routerlinkactive="active" href="/icc-ppw-u2-01Fundamentos/proyectos" class jsaction="click:;">Proyectos</a><a _ngcontent-ng-c584486 routerlink="/proyectos-dos" routerlinkactive="active" href="/icc-ppw-u2-01Fundamentos/proyectos-dos" class jsaction="click:;">Proyectos Dos</a><a _ngcontent-ng-c584486 routerlink="/formulariopage" routerlinkactive="active" href="/icc-ppw-u2-01Fundamentos/formulariopage" class="active" jsaction="click:;">Formulario</a></nav></app-nav-bar><router-outlet></router-outlet><app-formulariopage ngh="1"><div class="row"><div class="col"><form novalidate autocomplete="off" class="ng-untouched ng-pristine ng-invalid" jsaction="submit:;"><div class="mb-3"><label class="form-label">Nombre</label><input type="text" placeholder="Nombre del Usuario" formcontrolname="nombre" class="form-control ng-untouched ng-pristine ng-invalid" value jsaction="input:;blur:;compositionstart:;compositionend:;"><!----></div><div class="mb-3"><label class="form-label">Edad</label><input type="number" placeholder="Edad del Usuario" formcontrolname="edad" class="form-control ng-untouched ng-pristine ng-invalid" value="0" jsaction="input:;blur:;compositionstart:;compositionend:;"><!----></div><div class="mb-3"><label class="form-label">Correo</label><input type="email" placeholder="Correo electrónico" formcontrolname="correo" class="form-control ng-untouched ng-pristine ng-invalid" value jsaction="input:;blur:;compositionstart:;compositionend:;"><!----></div><div class="row"><div class="col"><button type="submit" class="btn btn-primary float-end"> Guardar </button></div></div></form></div></div></app-formulariopage><!----></app-root>
<script src="main-YY6O4WHQ.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"t":{"7":"t2","12":"t3","17":"t4"},"c":{"7":[],"12":[],"17":[]}},{"c":{"1":[{"i":"c749393984","r":1}]}}]}</script></body></html>`;